// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3AeeEusreKCjO0dyTRojFD7JOo_e3aa8',
    appId: '1:565970579599:web:0b4262a4dbc1da790a40fa',
    messagingSenderId: '565970579599',
    projectId: 'cea-lab-system',
    authDomain: 'cea-lab-system.firebaseapp.com',
    storageBucket: 'cea-lab-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9W9xUY4TgRNle0MjzrCQGj9vGPrTsaS4',
    appId: '1:565970579599:android:3683bcff518978090a40fa',
    messagingSenderId: '565970579599',
    projectId: 'cea-lab-system',
    storageBucket: 'cea-lab-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYg62QpWD5hSR9geEbbDAptRkaDrOF0rs',
    appId: '1:565970579599:ios:3e25e45c9adeafa50a40fa',
    messagingSenderId: '565970579599',
    projectId: 'cea-lab-system',
    storageBucket: 'cea-lab-system.firebasestorage.app',
    iosBundleId: 'com.example.ceaLabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYg62QpWD5hSR9geEbbDAptRkaDrOF0rs',
    appId: '1:565970579599:ios:3e25e45c9adeafa50a40fa',
    messagingSenderId: '565970579599',
    projectId: 'cea-lab-system',
    storageBucket: 'cea-lab-system.firebasestorage.app',
    iosBundleId: 'com.example.ceaLabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3AeeEusreKCjO0dyTRojFD7JOo_e3aa8',
    appId: '1:565970579599:web:eeab40967fbda4e90a40fa',
    messagingSenderId: '565970579599',
    projectId: 'cea-lab-system',
    authDomain: 'cea-lab-system.firebaseapp.com',
    storageBucket: 'cea-lab-system.firebasestorage.app',
  );

}